id: P003318
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-17 10:54:46.359517
source_metadata:
  id: bdr:W20873
  title: ཟབ་མོ་ནང་གི་དོན་ཉུང་ངུའི་ཚིག་གིས་རྣམ་པར་འགྲོལ་བ
  author: ''
  volumes:
    0fe9ba693d1b436694ac86288ab10a75:
      image_group_id: I2415
      title: ''
      volume_number: 1
      total_pages: 384
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
